# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rare Ruminare
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Rare Ruminare - 100% grass-fed organic Irish meat from animals that are free to graze on species-rich pastures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rareruminare.com" # the base hostname & protocol for your site

# deployment
host: 0.0.0.0
port: 5000

# Build settings
markdown: kramdown
permalink: none
