title: Rare Ruminare
email: your-email@domain.com
description: >
  Rare Ruminare - 100% grass-fed organic Irish meat from animals that are free to graze on species-rich pastures.
baseurl: ""
url: "http://www.rareruminare.com" # the base hostname & protocol for your site

social:
  - instagram:
    url: "https://www.instagram.com/rareruminare/"
    icon: "/images/instagram.svg"
  - facebook:
    url: "https://www.facebook.com/therareruminare/"
    icon: "/images/facebook.svg"

contact:
  tel:
    num: +353876418104
    display: 087 641 8104

  email: clive@rareruminare.com

# deployment
host: 0.0.0.0
port: 5000

# Build settings
markdown: kramdown
# permalink: none
permalink: /blog/:title

sass:
    style: compressed
