title: Rare Ruminare
email: your-email@domain.com
description: >
  Rare Ruminare - 100% grass-fed organic Irish meat from animals that are free to graze on species-rich pastures.
baseurl: ""
url: "http://www.rareruminare.com" # the base hostname & protocol for your site

social:
  - facebook:
    url: "https://www.facebook.com/therareruminare/"
    icon: "/images/facebook.svg"
  - instagram:
    url: "https://www.instagram.com/rareruminare/"
    icon: "/images/instagram.svg"

# deployment
host: 0.0.0.0
port: 5000

# Build settings
markdown: kramdown
permalink: none
